 name: "Kali Linux SSH"
  trigger_type: manual
  timeout_in: 120m
  container:
      image: kali-rolling:latest
      cpu: 8
      memory: 64G

 with:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        SSH_PASS: ${{ secrets.SSH_PASS }}
        NGROK_TIMEOUT: 25001
      

  Tmate_script:
      - bash tmate.sh

  Spam_script:
      - bash spam.sh
