name: "Kali Linux SSH"

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  kali-ssh:
    runs-on: ubuntu-latest # The host runner GitHub uses to run your jobs
    timeout-minutes: 120 # Sets the timeout to 120 minutes

    container:
      image: kalilinux/kali-rolling:latest # Correct image name
      options: --cpus 4 --memory 8g # Updated resource allocation to fit the limits

    env:
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }} # Pass secret for ngrok auth
      SSH_PASS: ${{ secrets.SSH_PASS }} # Pass secret for SSH password
      NGROK_TIMEOUT: 25001 # Set ngrok timeout

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # Check out the repository

    - name: Set up tmate (Optional for debugging)
      uses: mxschmitt/action-tmate@v3 # Optional step for debugging via SSH

    - name: Run Tmate Script
      run: |
        bash tmate.sh

    - name: Run Spam Script
      run: |
        bash spam.sh
